version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
profile = "hatchmark-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "IngestionBucketName=\"hatchmark-ingestion-bucket-36933227\" ProcessedBucketName=\"hatchmark-processed-bucket-36933227\""
image_repositories = []
