version = 0.1

[default.deploy.parameters]
stack_name = "hatchmark-authenticity-service-dev"
resolve_s3 = true
s3_prefix = "hatchmark-dev"
region = "us-east-1"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[prod.deploy.parameters]
stack_name = "hatchmark-authenticity-service-prod"
resolve_s3 = true
s3_prefix = "hatchmark-prod"
region = "us-east-1"
profile = "default"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "Environment=\"prod\""
image_repositories = []
