AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hatchmark Digital Authenticity Service - Simplified for Initial Deployment

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    Environment:
      Variables:
        PYTHONPATH: /opt/python
  HttpApi:
    CorsConfiguration:
      AllowOrigins: 
        - "http://localhost:3000"
        - "https://hatchmark-authenticity-service.vercel.app"
        - "*"
      AllowHeaders: 
        - "Content-Type"
        - "Authorization"
        - "X-Requested-With"
        - "Accept"
      AllowMethods: 
        - "GET"
        - "POST"
        - "OPTIONS"
        - "PUT"
      AllowCredentials: false
      MaxAge: 86400

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]

Resources:
  # S3 Buckets
  IngestionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'hatchmark-ingestion-${Environment}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'hatchmark-processed-${Environment}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # DynamoDB Table
  AssetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'hatchmark-assets-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: assetId
          AttributeType: S
        - AttributeName: perceptualHash
          AttributeType: S
      KeySchema:
        - AttributeName: assetId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PerceptualHashIndex
          KeySchema:
            - AttributeName: perceptualHash
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # SQS Queue (Fixed configuration)
  WatermarkingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'hatchmark-watermarking-${Environment}'
      VisibilityTimeout: 900
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 20

  # Lambda Functions
  GeneratePresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'hatchmark-generate-url-${Environment}'
      CodeUri: src/handlers/
      Handler: generate_presigned_url.lambda_handler
      Environment:
        Variables:
          INGESTION_BUCKET: !Ref IngestionBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref IngestionBucket
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /uploads/initiate
            Method: POST

  HashFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'hatchmark-hash-${Environment}'
      CodeUri: src/handlers/
      Handler: hashing_handler.lambda_handler
      Timeout: 60
      Environment:
        Variables:
          INGESTION_BUCKET: !Ref IngestionBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref IngestionBucket

  DynamoDBWriteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'hatchmark-dynamodb-write-${Environment}'
      CodeUri: src/handlers/
      Handler: dynamodb_write_handler.lambda_handler
      Environment:
        Variables:
          ASSETS_TABLE: !Ref AssetsTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref AssetsTable

  VerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'hatchmark-verify-${Environment}'
      CodeUri: src/handlers/
      Handler: verification_handler.lambda_handler
      Environment:
        Variables:
          ASSETS_TABLE: !Ref AssetsTable
          PROCESSED_BUCKET: !Ref ProcessedBucket
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AssetsTable
        - S3ReadPolicy:
            BucketName: !Ref ProcessedBucket
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /verify
            Method: POST

  DuplicateCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'hatchmark-duplicate-check-${Environment}'
      CodeUri: src/handlers/
      Handler: duplicate_check_handler.lambda_handler
      Timeout: 60
      Environment:
        Variables:
          ASSETS_TABLE: !Ref AssetsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AssetsTable
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /uploads/check-duplicate
            Method: POST

  # Step Functions State Machine (Simplified)
  HatchmarkWorkflow:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub 'HatchmarkWorkflow-${Environment}'
      DefinitionUri: workflow/state-machine.json
      DefinitionSubstitutions:
        HashFunctionArn: !GetAtt HashFunction.Arn
        DynamoDBWriteFunctionArn: !GetAtt DynamoDBWriteFunction.Arn
        WatermarkingQueueUrl: !Ref WatermarkingQueue
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref HashFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref DynamoDBWriteFunction
        - SQSSendMessagePolicy:
            QueueName: !GetAtt WatermarkingQueue.QueueName

Outputs:
  HttpApiUrl:
    Description: "HTTP API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-HttpApiUrl"
  
  IngestionBucketName:
    Description: "S3 bucket for file ingestion"
    Value: !Ref IngestionBucket
    Export:
      Name: !Sub "${AWS::StackName}-IngestionBucket"
  
  ProcessedBucketName:
    Description: "S3 bucket for processed files"
    Value: !Ref ProcessedBucket
    Export:
      Name: !Sub "${AWS::StackName}-ProcessedBucket"
  
  WatermarkingQueueUrl:
    Description: "SQS queue URL for watermarking tasks"
    Value: !Ref WatermarkingQueue
    Export:
      Name: !Sub "${AWS::StackName}-WatermarkingQueue"